### ISSUE TITLE
inifinte loop

### ISSUE THREAD

**Issue by igel0** [EasonNYC/DiscoBot#6]
I tested out my car functions.
I attached the usb ttl and i added some debug printf messages to see if the bytes were received, and they were. But for some reason the robot function isn’t called. When I halted execution it showed that it was stuck in an infinite loop because of an unexpected interrupt. Heres a screen shot.
You can see my printf’s in the branch test2.
Let me know what you think

![screen shot 2016-05-05 at 1 05 42 am](https://cloud.githubusercontent.com/assets/18508509/15036538/3b7221ce-125e-11e6-8ee6-783aa355a5f7.png)
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/18508509/15036540/3e98e1b2-125e-11e6-8729-1157efbcc1cf.png)

**Comment by igel0** [comment]
It may have had something to do with changing
` while(usart1_available() >= 3){`
ill change it back to `>3` and test it

**Comment by igel0** [comment]
after changing it to `>3` it doesn't show the infinite loop problem but its not calling the function. Well figure it out on Monday.

**Comment by EasonNYC** [comment]
I was planning to change it to > 2, since that would fix the problem. The compiler sounds like it is optimizing out callme() . Or perhaps the stop function is being optimized. I wonder placing the 'volatile' keyword in front of the callme definition as well as in front of our motor functions is in order...

**Comment by igel0** [comment]
it probably was the >3 thing.
